name: 'Run C/C++test'
description: 'A GitHub Action for running Parasoft C/C++test analysis.'
author: 'Parasoft'
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  installDir:
    description: 'Installation folder of Parasoft C/C++test. If not specified, cpptestcli executable will be searched on $PATH.'
    required: false
  workingDir:
    description: 'Working directory for running C/C++test.'
    required: false
    default: ${{ github.workspace }}
  compilerConfig:
    description: 'Identifier of a compiler configuration. Ensure you specify the configuration that matches your compiler.'
    required: false
    default: 'gcc_9-64' 
  testConfig:
    description: 'Test configuration to be used when running code analysis.'
    required: false
    default: 'builtin://Recommended Rules'
  reportDir:
    description: 'Output folder for analysis reports.'
    required: false
    default: 'reports'
  reportFormat:
    description: 'Format of analysis reports.'
    required: false
    default: 'xml,html,sarif'
  input:
    description: 'Input scope for analysis - usually cpptestscan.bdf or compile_commands.json.'
    required: false
    default: 'cpptestscan.bdf'
  commandLinePattern:
    description: 'Command line pattern for running C/C++test.'
    required: false 
    default: '${cpptestcli} -compiler "${compilerConfig}" -config "${testConfig}" -property report.format=${reportFormat} -report "${reportDir}" -module . -input "${input}"'
runs:
  using: 'node12'
  main: 'dist/index.js'
