name: 'Run C/C++test'
description: 'A GitHub Action for running Parasoft C/C++test analysis.'
author: 'Parasoft'
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  cliArgs:
    description: 'Command line arguments for cpptestcli executable.'
    required: false
    default: '-compiler gcc_7-64 -config "builtin://Recommended Rules" -module . -property report.format=sarif,xml,html -input build/compile_commands.json'
  workingDir:
    description: 'Path to working directory. If not specified, $github.workspace will be used.'
    required: false
    default: ${{ github.workspace }}
  installDir:
    description: 'Path to folder containing cpptestcli executable. If not specified, cpptestcli executable will be searched on $PATH.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
